// Discord情報マッピングデータ
const discordMapping = {
    '藤澤秀彰': { discord: '藤澤', discordId: '' },
    '鈴木裕介': { discord: 'ゆう', discordId: 'exuberant_pomelo_29770' },
    '福井康大': { discord: 'yasu0016', discordId: '' },
    '俵健太郎': { discord: 'たわら', discordId: '' },
    '進藤勇輝': { discord: 'シン', discordId: '' },
    '佐藤諒駿': { discord: 'アキ', discordId: '5493' },
    '杉平涼': { discord: '涼', discordId: '' },
    '松本和久': { discord: 'kazu7106', discordId: '' },
    '松田陽平': { discord: 'Yohei', discordId: '' },
    '井上純也': { discord: '純', discordId: '' },
    '根塚陽己': { discord: 'いっきゅうさん', discordId: '9839' },
    '藤原綜太郎': { discord: 'えいと', discordId: '8888' },
    '石島秀峰': { discord: 'セバス', discordId: 'sebastian0720' },
    '佐藤亜美': { discord: 'あみ', discordId: '' },
    '塚本真伍': { discord: 'セツ', discordId: 'secchin_a' },
    '湊翔太郎': { discord: 'Minato', discordId: '10193710' },
    '鈴木菜摘': { discord: 'なつみ', discordId: '' },
    '松島徹': { discord: 'まっつん', discordId: '' },
    '粟津律子': { discord: 'リツ姉', discordId: '' },
    '榎本高也': { discord: '榎本', discordId: '' },
    '石垣吉規': { discord: 'yoshi_is', discordId: '' },
    'ブル': { discord: 'bullsan44', discordId: '' },
    '鈴木康太': { discord: 'kota', discordId: '7ps' },
    '奥村拓哉': { discord: 'okuruma1918', discordId: '' },
    '池本湊了汰': { discord: 'sota_ilemoto', discordId: '' },
    '松本竜季': { discord: 'しぶさわ', discordId: 'shibusawakun' },
    '西島颯人': { discord: 'ハザマ', discordId: 'Yato#3447' },
    '山縣誠二': { discord: 'やまがたせいじ', discordId: '8166' },
    '綿貫桂太': { discord: 'keita2432', discordId: '' },
    '清水暁': { discord: 'ugachi', discordId: '' },
    '中村意央里': { discord: 'iori3765', discordId: '' },
    '島守勇次': { discord: 'しま', discordId: 'shima06293' },
    '千吉良俊充': { discord: 'toshi0050', discordId: '' },
    '岩下未誉子': { discord: 'min_0406', discordId: '' },
    '安田滉一': { discord: 'shoku', discordId: 'shoku6718' },
    '真木智之': { discord: 'むちの王', discordId: 'saamonabokado' },
    '吉嵜俊一郎': { discord: 'パコル', discordId: 'pakiru5029' },
    '今井一真': { discord: 'kazumaimai', discordId: '' },
    '平野理絵': { discord: 'ユーリズ', discordId: 'yulis_family_face' },
    '内田泰文': { discord: 'aiaitoyonaka', discordId: '' },
    '増田凌一': { discord: 'mastarisk', discordId: 'pamera5816' },
    '新保友望奈': { discord: 'ちょこ', discordId: 'chocochoco_55' },
    '市川佳奈': { discord: 'kana', discordId: 'kana.0822_51355' },
    '渡邉智大': { discord: 'なべとも', discordId: 'botan9426' },
    '泉田祐輝': { discord: 'ゆうき', discordId: 'yuki08yuki' },
    '永井克幸': { discord: '克', discordId: 'katsu614' },
    '茂木一幸': { discord: 'acee2024', discordId: '' },
    '松田圭右': { discord: 'けいすけ', discordId: 'kei07279' },
    '松村遼河': { discord: 'ryoga_matsumura', discordId: 'powerful_badger_31777' },
    '平岩遼志': { discord: 'りょう', discordId: 'jubilant_hamster_65393' },
    '佐藤一気': { discord: 'いっき', discordId: 'ikki1121' },
    '照井紀臣': { discord: 'テリー', discordId: 'teri20211001' },
    '坂詰宣人': { discord: 'Hisato', discordId: 'hisato1995' },
    '中悠太': { discord: 'レナス33', discordId: 'renasu7072' },
    '小林千泰': { discord: 'ちい', discordId: 'chii9198' },
    '廣田一敬': { discord: 'カズ', discordId: 'slapfill' },
    '鈴木智弘': { discord: 'ともひろ', discordId: 'zhihong_84137' },
    '小島啓輔': { discord: 'KEI', discordId: 'keizbr_26587' },
    '尾崎勇哉': { discord: 'オザキ/マーリン', discordId: 'zakiozaki' },
    '佐々木透': { discord: 'とおる', discordId: '' },
    '小林和貴': { discord: 'こばし', discordId: '' },
    '日高悠河': { discord: 'ゆうが', discordId: '' },
    '江口達宏': { discord: 'こーいち', discordId: '' },
    '東出教若': { discord: 'Natu', discordId: '' },
    '出田竜也': { discord: 'Nori', discordId: 'rai_east' },
    '長田一': { discord: '長田一', discordId: '' },
    '市橋慎士': { discord: 'shinji', discordId: '' },
    '今井奎介': { discord: 'けいすけ', discordId: 'maimai0553' },
    '中西航平': { discord: 'kohei nakanishi', discordId: '' },
    '熊谷瑞奈美': { discord: 'みなみ', discordId: '' },
    '内野真子': { discord: 'こんぶ', discordId: 'marukonbu' },
    '稲垣真裕': { discord: 'ina.1984', discordId: '' },
    '清田宇宙': { discord: 'ロータス', discordId: 'shiva' },
    '猪野倫哉': { discord: 'tomoya', discordId: '' },
    '松垣友': { discord: 'tomodachi9655', discordId: '' },
    '篠崎弘多': { discord: '篠崎弘多（シノザキコウタ）', discordId: '' },
    '市村智': { discord: 'satoshi', discordId: '' },
    '今野大輔': { discord: '若葉の道士 だいすけ', discordId: 'poporo8289' },
    '巾崎由紀子': { discord: 'ハバユキコ', discordId: '' },
    '籾山銀河': { discord: 'galaxy', discordId: '' },
    '坂之上颯人': { discord: 'さか', discordId: '' },
    '氏家威吹': { discord: 'ibuki', discordId: '340i1' },
    '黒柳朱音': { discord: 'Deck Brown', discordId: '' },
    '国安あずみ': { discord: 'az', discordId: 'az613' },
    '阪本巳玖也': { discord: 'nickname', discordId: 'nickname_41003' },
    '坂本研太朗': { discord: '千賀', discordId: 'senga_sn' },
    '藤井徹': { discord: 'Yuya', discordId: 'yuyaperco' },
    '吉岡佑弥': { discord: 'きょうへい', discordId: '' },
    '佐藤恭平': { discord: 'も', discordId: '' },
    '小渕桃子': { discord: 'こーいち', discordId: '' },
    '森岡裕之': { discord: 'ひろゆき', discordId: '' },
    '遠藤瑛太': { discord: 'えいた', discordId: '' },
    '亀井悠': { discord: '悠', discordId: 'hrk_0320' },
    '伊藤英哉': { discord: '伊藤英哉', discordId: 'zouyi058_20077' },
    '小杉沙里衣': { discord: 'さりこ', discordId: 'sariko80jp' },
    '薄田京': { discord: '薄田京', discordId: 'kyo_sskd' },
    '淺沼佳那子': { discord: 'kanako9075', discordId: '' },
    '山田大将': { discord: 'たいしょう', discordId: 'taishiyou_67698' },
    '永野福三': { discord: 'NAGANO(zoo)', discordId: 'zoo24hdasa' },
    '中根滉介': { discord: 'こうすけ', discordId: 'kousuke3338' },
    '山田剛': { discord: 'つよぼむ', discordId: 'つよぼむ' },
    '田原璃音': { discord: '凪 りおんせ', discordId: '' },
    '淺利勇斗': { discord: 'Yuto', discordId: 'yuto07350' },
    '片山裕子': { discord: 'ひろこ', discordId: 'hr7233' },
    '水林麻里恵': { discord: 'mari', discordId: 'mari_70085' },
    '榎本知佳': { discord: 'えのもっちゃん', discordId: 'enokibook' },
    '畠田はな': { discord: 'ハルハナ', discordId: 'haruhana6896' },
    '上村徹雄': { discord: 'てつを', discordId: 'tetsuwow_88688' },
    '渡邊敦子': { discord: 'えび', discordId: 'ebi' },
    '伊藤奏衣': { discord: '奏衣', discordId: 'zouyi058' },
    '片桐瞭': { discord: 'neogiri', discordId: '' },
    '渕上哲汰': { discord: 'tetsuta21', discordId: '' },
    '宮崎弘登': { discord: 'hiroto', discordId: 'miyatorisu1049' }
};

// データベース更新関数
function updateMembersWithDiscord(membersDatabase) {
    return membersDatabase.map(member => {
        const discordInfo = discordMapping[member.name];
        if (discordInfo) {
            return {
                ...member,
                discord: discordInfo.discord,
                discordId: discordInfo.discordId
            };
        }
        return {
            ...member,
            discord: '',
            discordId: ''
        };
    });
}

console.log('Discord mapping data loaded. Use updateMembersWithDiscord() to apply.');
